projects:
  app:
    schemaPath: packages/app/src/app/graphql/schema.graphql
    extensions:
      endpoints:
        prod: 'https://codesandbox.io/api/graphql'
        staging: 'https://codesandbox.stream/api/graphql'
        dev: 'http://localhost:4000/api/graphql'
