version: 2

jobs:
  build-dependencies:
    docker:
      - image: circleci/node:9.0
    working_directory: ~/codesandbox-client
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ./packages/app/node_modules
            - ./packages/codesandbox-api/node_modules
            - ./packages/common/node_modules
            - ./packages/homepage/node_modules
            - ~/.yarn-cache
      - run:
          name: Build
          command: yarn build:dependents
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/codesandbox-client

  build-prod:
    docker:
      - image: circleci/node:9.0
    working_directory: ~/codesandbox-client
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      # We do this to compare sizes from previous builds
      - restore_cache:
          key: prod-build-cache-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
      - run:
          name: Build Application
          command: yarn build:prod
      - save_cache:
          key: prod-build-cache-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
            - ./packages/app/www

  test-integrations:
    docker:
      - image: codesandbox/node-puppeteer
    working_directory: ~/codesandbox-client
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Start Test Server
          command: yarn start:test
          background: true
      - run:
          name: Test Integrations
          command: |
            sleep 6
            yarn test:integrations
      - store_artifacts:
          path: packages/app/integration-tests/tests/__image_snapshots__/__diff_output__
          destination: image_snapshot_diff
  
  test-jest:
    docker:
      - image: circleci/node:9.0
    working_directory: ~/codesandbox-client
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Test
          command: yarn test

  lint:
    docker:
      - image: circleci/node:9.0
    working_directory: ~/codesandbox-client
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint
          command: yarn lint

  deploy:
    docker:
      - image: circleci/node:9.0
    working_directory: ~/codesandbox-client
    steps:
      - restore_cache:
          key: prod-build-cache-{{ .Environment.CIRCLE_BUILD_NUM }}
      - run:
          name: Deploy
          command: echo DEPLOY!
        
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-dependencies
      - test-integrations:
          requires:
            - build-dependencies
      - test-jest:
          requires:
            - build-dependencies
      - lint:
          requires:
            - build-dependencies
      - build-prod:
          requires:
            - build-dependencies
      - hold:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - build-prod
            - lint
            - test-integrations
            - test-jest
      - deploy:
          requires:
            - hold



