version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node:9.2.1
    working_directory: ~/codesandbox-client
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f7:f1:e6:60:96:24:d9:cd:1b:8b:c0:34:e7:ee:fa:82"
      - run:
          name: Add key to known_hosts
          command: echo "ssh.codesandbox.io ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKyKbuMPJSETTyPRRJVOeC5I8j7wyUMW8HYheg7cN71eKTuw55tkoygxI59BvNi/CAyCnRT5LnxZhvrq9nSlPYc=" >> ~/.ssh/known_hosts
      - deploy:
          command: sh ./deploy.sh

workflows:
  version: 2
  build-and-test:
    jobs:
      - deploy
