version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9.0
    working_directory: ~/codesandbox-client
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install && yarn add puppeteer -W
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ~/.yarn-cache
      - run:
          name: Workaround for https://github.com/GoogleChrome/puppeteer/issues/290
          command: sh ./packages/app/integration-tests/scripts/workaround-puppeteer-issue-290.sh
      - run:
          name: Build
          command: yarn build
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/codesandbox-client

  test-integrations:
    docker:
      - image: circleci/node:9.0
    working_directory: ~/codesandbox-client
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Start Test Server
          command: yarn start:test
          background: true
      - run:
          name: Test Integrations
          command: |
            sleep 6
            yarn test:integrations
      - store_artifacts:
          path: packages/app/integration-tests/tests/__image_snapshots__/__diff_output__
          destination: image_snapshot_diff
  
  test-jest:
    docker:
      - image: circleci/node:9.0
    working_directory: ~/codesandbox-client
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Test
          command: yarn test

  lint:
    docker:
      - image: circleci/node:9.0
    working_directory: ~/codesandbox-client
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint
          command: yarn lint
        
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test-integrations:
          requires:
            - build
      - test-jest:
          requires:
            - build
      - lint:
          requires:
            - build


